#
# Codecov Docs:
# https://docs.codecov.com/docs
#
# Codecov Reports:
# https://app.codecov.io/gh/chora-io/web
#
coverage:
  precision: 2
  round: down
  range: 70...100
  status:
    project:
      default:
        threshold: 1%
      faucet:
        paths:
          - "apps/faucet"
      groups:
        paths:
          - "apps/groups"
      landing:
        paths:
          - "apps/landing"
      ledger:
        paths:
          - "apps/ledger"
      registry:
        paths:
          - "apps/registry"
      chora:
        paths:
          - "packages/chora"
      cosmos:
        paths:
          - "packages/cosmos"
    changes: false

comment:
  layout: "diff, flags, files"
  behavior: default
  require_changes: true
