version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/apps/faucet"
    schedule:
      interval: daily
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/apps/groups"
    schedule:
      interval: daily
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/apps/landing"
    schedule:
      interval: daily
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/apps/ledger"
    schedule:
      interval: daily
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/apps/registry"
    schedule:
      interval: daily
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/packages/chora"
    schedule:
      interval: daily
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/packages/cosmos"
    schedule:
      interval: daily
    open-pull-requests-limit: 5
